-- 5
insert into tests (title) values ('grammar'),('english'),('math'),('bilogy'),('logic');
-- 30
insert into questions (text,tid) values ('What weird food combinations do you really enjoy?',1),
('What social stigma does society need to get over?',1),
('What food have you never eaten but would really like to try?',1),
('What''s something you really resent paying for?',1),
('What would a world populated by clones of you be like?',1),
('Do you think that aliens exist?',1),
('What are you currently worried about?',1),
('Where are some unusual places you''ve been?',1),
('Where do you get your news?',2),
('What are some red flags to watch out for in daily life?',2),
('What movie can you watch over and over without ever getting tired of?',2),
('When you are old, what do you think children will ask you to tell stories about?',2),
('If you could switch two movie characters, what switch would lead to the most inappropriate movies?',3),
('What inanimate object would be the most annoying if it played loud upbeat music while being used?',3),
('When did something start out badly for you but in the end, it was great?',3),
('How would your country change if everyone, regardless of age, could vote?',3),
('What animal would be cutest if scaled down to the size of a cat?',3),
('If your job gave you a surprise three day paid break to rest and recuperate, what would you do with those three days?',3),
('What''s wrong but sounds right?',3),
('What''s the most epic way you''ve seen someone quit or be fired?',3),
('If you couldn''t be convicted of any one type of crime, what criminal charge would you like to be immune to?',3),
('What''s something that will always be in fashion, no matter how much time passes?',4),
('What actors or actresses play the same character in almost every movie or show they do?',4),
('In the past people were buried with the items they would need in the afterlife, what would you want buried with you so you could use it in the afterlife?',4),
('What''s the best / worst practical joke that you''ve played on someone or that was played on you?',5),
('Who do you go out of your way to be nice to?',5),
('Where do you get most of the decorations for your home?',5),
('What food is delicious but a pain to eat?',5),
('Who was your craziest / most interesting teacher',5),
('What “old person” things do you do?',5);
-- 190 
insert into answers (text,qid,correct) values ('Scooter Across Australia', 1, 1),
('Live on the Streets', 1, 0),
('African clawless otter Aonyx capensis', 1, 0),
('Ant (unidentified) unavailable', 1, 0),
('African jacana Actophilornis africanus', 2, 1),
('African polecat Ictonyx striatus', 2, 0),
('For sale on behalf of Make-A-Wish', 2, 0),
('Buy a Stranger Lunch', 2, 0),
('Act in a Play', 3, 1),
('Throw a Dart at a Map and Visit the Country It Lands On', 3, 0),
('For Auction on behalf of Camp Quality', 3, 0),
('Asian lion Panthera leo persica', 3, 0),
('Asian water dragon Physignathus cocincinus', 3, 0),
('Australian pelican Pelecanus conspicillatus', 3, 0),
('Australian sea lion Neophoca cinerea', 3, 0),
('Adouri', 4, 1),
('Sumo Wrestling', 4, 0),
('Feature in a Bollywood Movie', 4, 0),
('Surf Safari', 4, 0),
('Speed Dating', 4, 0),
('Street Performance', 5, 1),
('Cross a Desert', 5, 0),
('American badger Taxidea taxus', 5, 0),
('American beaver Castor canadensis', 5, 0),
('Playboy Mansion', 5, 0),
('Leaning Tower of Pisa', 5, 0),
('Live with a Tribe for One Week', 5, 0),
('Anteater, giant Myrmecophaga tridactyla', 5, 0),
('Armadillo, common long-nosed Dasypus novemcinctus', 6, 1),
('Publish an Article', 6, 0),
('Hit a Hole in One', 7, 1),
('Invent Something', 7, 0),
('Asian false vampire bat Megaderma spasma', 7, 0),
('Antelope, roan Hippotragus equinus', 7, 0),
('Armadillo, seven-banded Dasypus septemcincus', 8, 1),
('Asiatic jackal Canis aureus', 8, 0),
('Ultimate Prank', 8, 0),
('Minister a Wedding', 8, 0),
('Land Diving', 8, 0),
('Grow a Beard', 8, 0),
('Make a London Guard Laugh', 9, 1),
('African red-eyed bulbul Pycnonotus nigricans', 9, 0),
('African black crake Limnocorax flavirostra', 9, 0),
('Learn Salsa', 9, 0),
('Dad’s Dream Car', 9, 0),
('Be in a Hollywood Movie', 9, 0),
('Meet Another ‘Sebastian Terry’', 10, 1),
('Raise $100,000 for Camp Quality', 10, 0),
('African buffalo Snycerus caffer', 10, 0),
('For Auction on behalf of Camp Quality', 10, 0),
('Australian spiny anteater Tachyglossus aculeatus', 10, 0),
('Armadillo, nine-banded Dasypus novemcinctus', 10, 0),
('Arctic fox Alopex lagopus', 10, 0),
('American black bear Ursus americanus', 10, 0),
('Alpaca Lama pacos', 11, 1),
('American crow Corvus brachyrhynchos', 11, 0),
('Statue of Liberty', 11, 0),
('Ice Fishing', 11, 0),
('Walk Across a Country', 12, 1),
('Running with Bulls', 12, 0),
('Eiffel Tower', 12, 0),
('Admiral, indian red Vanessa indica', 12, 0),
('Arctic hare Lepus arcticus', 12, 0),
('American racer Coluber constrictor', 13, 1),
('Machu Picchu', 13, 0),
('American bighorn sheep Ovis canadensis', 13, 0),
('Chase a Tornado', 13, 0),
('Treacherous Trek', 13, 0),
('American bison Bison bison', 14, 1),
('Agile wallaby Macropus agilis', 14, 0),
('Crazy Bid', 14, 0),
('Asian water buffalo Bubalus arnee', 14, 0),
('Asian elephant Elephas maximus bengalensis', 14, 0),
('Perform an Original Song', 15, 1),
('Haunted House', 15, 0),
('Agama lizard (unidentified) Agama sp.', 15, 0),
('African ground squirrel (unidentified) Xerus sp.', 15, 0),
('Stand-Up Comedy Routine', 15, 0),
('Complete a Triathlon', 15, 0),
('Kiss a Celebrity', 15, 0),
('Work at an Orphanage', 16, 1),
('Sports Streak', 16, 0),
('Foreign Aid', 16, 0),
('Have Something Named After Me', 16, 0),
('Surf River Wave', 16, 0),
('Avocet, pied Recurvirostra avosetta', 16, 0),
('Asiatic wild ass Equus hemionus', 16, 0),
('Antechinus, brown Antechinus flavipes', 17, 1),
('Go on an Adventure', 17, 0),
('Live on a Desert Island for One Week', 17, 0),
('Be a Contestant on a TV Game Show', 17, 0),
('Whale Shark Swim', 17, 0),
('Be in a Dance Video Clip', 18, 1),
('Bet $1000 on Black (Roulette)', 18, 0),
('Tantric Lesson', 18, 0),
('Hitchhike Across America', 18, 0),
('Sydney Opera House', 18, 0),
('Alligator, mississippi Alligator mississippiensis', 18, 0),
('American alligator Alligator mississippiensis', 18, 0),
('Andean goose Chloephaga melanoptera', 18, 0),
('American woodcock Scolopax minor', 19, 1),
('Albatross, galapagos Diomedea irrorata', 19, 0),
('African pied wagtail Motacilla aguimp', 19, 0),
('African elephant Loxodonta africana', 19, 0),
('Plant a Tree', 19, 0),
('Visit a Fortune Teller', 19, 0),
('Own a Company', 20, 1),
('Skydive Naked', 20, 0),
('Attend an Extreme Religious Ceremony', 20, 0),
('Muster Cattle', 20, 0),
('Endurance Tandem Bike Ride', 20, 0),
('Be a Horse Jockey', 20, 0),
('Kremlin', 20, 0),
('Anaconda (unidentified) Eunectes sp.', 20, 0),
('American marten Martes americana', 20, 0),
('Amazon parrot (unidentified) Amazona sp.', 20, 0),
('American buffalo Bison bison', 20, 0),
('Antelope, sable Hippotragus niger', 20, 0),
('Asian openbill Anastomus oscitans', 20, 0),
('Arctic ground squirrel Spermophilus parryii', 21, 1),
('Great Wall of China', 21, 0),
('Stay Awake for Seventy-Two Hours', 21, 0),
('African darter Anhinga rufa', 21, 0),
('African lion Panthera leo', 21, 0),
('African bush squirrel Paraxerus cepapi', 21, 0),
('Albatross, waved Diomedea irrorata', 21, 0),
('African porcupine Hystrix cristata', 21, 0),
('Join a Protest', 21, 0),
('Burning Man Festival', 22, 1),
('Visit a Death Row Inmate', 22, 0),
('Cycle through Cuba', 22, 0),
('African skink Mabuya spilogaster', 22, 0),
('African wild cat Felis silvestris lybica', 22, 0),
('Meditation', 22, 0),
('Crash a Red Carpet', 22, 0),
('Face a Shane Warne Over', 23, 1),
('Agouti Dasyprocta leporina', 23, 0),
('African fish eagle Haliaetus vocifer', 23, 0),
('Sail the Seas', 23, 0),
('Say Yes to Everything for One Week', 23, 0),
('American Virginia opossum Didelphis virginiana', 23, 0),
('Ass, asiatic wild Equus hemionus', 24, 1),
('Deliver a Baby', 24, 0),
('African snake (unidentified) unavailable', 24, 0),
('Alligator, american Alligator mississippiensis', 25, 1),
('African lynx Felis caracal', 25, 0),
('Aardwolf Proteles cristatus', 25, 0),
('Marathon (Iron Man)', 25, 0),
('Get Shot', 25, 0),
('Be a Team Mascot for a Day', 25, 0),
('Taj Mahal', 25, 0),
('Catch a Thief', 25, 0),
('Participate in a Boxing Match', 25, 0),
('Naked Rugby', 25, 0),
('Get a Tattoo', 25, 0),
('Argalis Ovis ammon', 25, 0),
('Asian red fox Vulpes vulpes', 25, 0),
('Asian foreset tortoise Manouria emys', 26, 1),
('Antelope, four-horned Tetracerus quadricornis', 26, 0),
('Find My Family Tree', 26, 0),
('Olympic Ski Jump', 26, 0),
('Pyramid of Giza', 26, 0),
('Pose Nude', 26, 0),
('Marry a Stranger in Vegas', 27, 1),
('Be in a Medical Trial', 27, 0),
('Go to Timbuktu', 27, 0),
('Be a Weaponless & Harmless Matador', 27, 0),
('Read the National TV Weather Report', 27, 0),
('Anteater, australian spiny Tachyglossus aculeatus', 27, 0),
('Arctic lemming Dicrostonyx groenlandicus', 28, 1),
('Australian brush turkey Alectura lathami', 28, 0),
('Australian magpie Gymnorhina tibicen', 28, 0),
('Australian masked owl Tyto novaehollandiae', 28, 0),
('Throw a Party', 28, 0),
('Save a Life', 28, 0),
('Easter Island Moai', 28, 0),
('African wild dog Lycaon pictus', 28, 0),
('Publish a Book', 29, 1),
('One Week’s Silence', 29, 0),
('Help a Stranger', 29, 0),
('Learn French', 29, 0),
('Challenge a World Champion', 29, 0),
('Arboral spiny rat Echimys chrysurus', 29, 0),
('Antelope ground squirrel Ammospermophilus nelsoni', 29, 0),
('Arctic tern Sterna paradisaea', 30, 1),
('Armadillo, giant Priodontes maximus', 30, 0),
('Azaras zorro Pseudalopex gymnocercus', 30, 0),
('Represent a Country at Something', 30, 0),
('Guinness World Record', 30, 0),
('Build Something', 30, 0);